version: '3'

services:
  backend:
    build:
      context: ../learning-labyrinth-backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy

  database:
    image: mysql/mysql-server:latest
    ports:
      - "3306:3306"
    volumes:
      - ./data:/var/lib/mysql
    environment:
      MYSQL_USER: "admin"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "labyrinth_db"
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  frontend:
    build:
      context: ../learning-labyrinth-frontend
      dockerfile: Dockerfile
    ports: 
      - "3000:3000"